# Generated by Django 3.2.6 on 2021-08-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
