# Generated by Django 3.2.5 on 2021-08-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_main', '0002_food_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food_data',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
