# Generated by Django 3.2.5 on 2021-08-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_main', '0003_auto_20210818_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('fno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('path', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'food',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='food_data',
            table='food_data',
        ),
        migrations.CreateModel(
            name='attribute',
            fields=[
                ('fno', models.OneToOneField(db_column='fno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='delivery_main.food')),
                ('sense', models.CharField(max_length=20)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('good', models.IntegerField(blank=True, null=True)),
                ('bad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attribute',
                'managed': False,
            },
        ),
    ]
